server:
  port: 55
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # 不限制请求体大小

spring:
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  application:
    name: file-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: naocs
  rabbitmq:
    host: 127.0.0.1
    port: 5682
    username: guest
    password: guest
    virtual-host: /

# minIO配置
minio:
  endpoint: http://127.0.0.1:9000     # MinIO服务地址
  fileHost: http://127.0.0.1:9000     # 文件地址host
  bucketName: wechat                  # 存储桶bucket名称
  accessKey: root                     # 用户名
  secretKey: 12345678                 # 密码


# 日志级别
logging:
  level:
    root: info