server:
  port: 88
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # 不限制请求体大小

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  application:
    name: auth-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: naocs


# 日志级别
logging:
  level:
    root: info