server:
  port: 77
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # 不限制请求体大小


spring:
  datasource: # 数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时间(毫秒)
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长(毫秒)
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 18000000 # 连接池的最大生命时长(毫秒)
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  application:
    name: main-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: naocs



# 日志级别
logging:
  level:
    root: info