server:
  port: 1000
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # 不限制请求体大小


spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: naocs
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:           # 路由配置信息(数组/list)
        - id: authRoute # 每项路由规则都有一个唯一的id编号，可以自定义
          uri: lb://auth-service # lb=负载均衡，会动态寻址
          predicates:
            - Path=/passport/**
        - id: fileRoute
          uri: lb://file-service
          predicates:
            - Path=/file/**,/static/**
        - id: mainRoute
          uri: lb://main-service
          predicates:
            - Path=/userinfo/**,/friendRequest/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true


# 日志级别
logging:
  level:
    root: info


blackIp:
  continueCounts: 3 # ip连续请求次数
  timeInterval: 60 # ip判断的时间间隔，单位：秒
  limitTimes: 30 # 黑名单ip限制的时间，单位：秒